### ISSUE TITLE
Stable version of parity instead of specific version

### ISSUE THREAD

**Issue by edisinovcic** [vincentserpoul/parityPoA#1] opened 2019-05-06 17:22 UTC
Shouldn't stable be a better option considering that parity only keeps most recent images on docker hub?

**Comment by vincentserpoul** [comment] 2019-05-07 02:11
I would love to do that, but the issue is that the setup outcome has been extremely unreliable when new version are release.
If you test with another recent version that works, I would definitely accept PRs though.

**Comment by edisinovcic** [comment] 2019-05-07 08:09
It's definitelly not a best option as specific version are always a better solution to use with docker images. WIll do a PR shortly.

**Comment by vincentserpoul** [comment] 2019-05-07 08:47
Sorry, I might not have been clear in my explanation.
Stable is a moving target.
I've been upgrading this repo regularly for quite a while to stable versions, and from time to time, the build was broken and needed to be fixed by changing things (config changes, docker user changes).

If we want to keep a repeatable build, we can't use the moving stable tag, which can break the build at one point.

If you have tested with the latest stable though, it would be great to update with the build it corresponds to, but not with the "stable" tag, which can potentially break the build in the future.

thank you!

**Comment by edisinovcic** [comment] 2019-05-07 08:52
It's been updated to 2.5.0

**Closed as completed** 2019-05-08 08:42 UTC
